In [2]:
22+44

66

this is markdown cell

In [4]:
pip --version

pip 21.0.1 from /home/bbborisk/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [7]:
my_list = [1,2,3]
n = np.array(my_list)

In [9]:
print(n)

[1 2 3]


In [10]:
n

array([1, 2, 3])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.eye(5,5) #dijagonala

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.linspace(0,10,3) #daje 3 broja izmedju 0 i 10 sa jednakim rastojanjima izmedju
np.linspace(0,1,22)

array([0.        , 0.04761905, 0.0952381 , 0.14285714, 0.19047619,
       0.23809524, 0.28571429, 0.33333333, 0.38095238, 0.42857143,
       0.47619048, 0.52380952, 0.57142857, 0.61904762, 0.66666667,
       0.71428571, 0.76190476, 0.80952381, 0.85714286, 0.9047619 ,
       0.95238095, 1.        ])

In [35]:
mn = np.arange(0,50,2)

In [36]:
mn

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

mn.reshape(25,1) #pravi od niza brojeva niz od 25 1-dimenzionih matrica

In [46]:
small = np.linspace(0,1,15)

In [48]:
small.resize(3,5)

In [49]:
small

array([[0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429],
       [0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714],
       [0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ]])

**razlika izmedju resize i reshape jeste sto resize menja promenjivu, dok reshape samo prikazuje reshape, ali promenjiva ostaje ista kakava je i bila

In [56]:
np.random.rand(10,2) #nasumicna matrica od 10 2dimenyionih matrica semplovanih sa uniformne raspodela (0,1)
np.random.randn(10,2) #nasumicna matrica od 10 2dimenyionih matrica, semplovanih sa standardne (normalne) raspodele(-n.n))


array([[ 1.0853711 ,  0.86333549],
       [-0.44428876, -0.61169188],
       [ 0.17082926, -0.36541883],
       [ 1.29886604, -2.73667789],
       [ 0.41017135, -0.92664669],
       [ 0.24621216, -1.18136488],
       [ 1.41436465,  0.93830043],
       [ 1.07840481, -1.33054608],
       [-0.40236443,  0.04217584],
       [ 0.77720842, -0.44320488]])

In [15]:
s = np.random.randint(10,50,10)
s



array([12, 16, 10, 49, 33, 31, 12, 26, 10, 41])

In [17]:
s.resize(2,4)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [20]:
s[2:5]

array([10, 49, 33])

In [24]:
mm=np.arange(64)

In [23]:
mm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62])

In [25]:
mm.resize(8,8)

In [26]:
mm

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [27]:
mm[2,4] #daje 2 kolonu, 4 red (krece od nule ofc)

20

In [29]:
mm[3,2:4] #daje u 3 koloni niz od 2 do 4 indeksa

array([26, 27])

In [31]:
mm[3:] #sve kolone posle trece

array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [32]:
mm[3:,3:] #po istoj logici, red i kolone od trece pa nadalje

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [33]:
mm[mm>24] #daje sve cifre ve'e od 24

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63])

In [34]:
mm<24 # daje info da da li je svaka cifra ve'a od 24

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [36]:
mm[mm>10]=10 #svaki broj veci od deset postavlja na 10 (broadcasting)
mm

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [38]:
mm1 = mm[3:,3:]
mm1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [39]:
 mm1_copy = mm1.copy() #pravi kopiju 

In [40]:
import pandas as pd

In [56]:
df= pd.read_csv("day.csv")

In [48]:
df.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [57]:
df.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0   
1        2  2011-01-02       1   0     1        0        0           0   
2        3  2011-01-03       1   0     1        0        1           1   
3        4  2011-01-04       1   0     1        0        2           1   
4        5  2011-01-05       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [60]:
data = df.copy()

In [61]:
data.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0   
1        2  2011-01-02       1   0     1        0        0           0   
2        3  2011-01-03       1   0     1        0        1           1   
3        4  2011-01-04       1   0     1        0        2           1   
4        5  2011-01-05       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [62]:
data["temp"]

0      0.344167
1      0.363478
2      0.196364
3      0.200000
4      0.226957
         ...   
726    0.254167
727    0.253333
728    0.253333
729    0.255833
730    0.215833
Name: temp, Length: 731, dtype: float64

In [75]:
data[["temperature","atmospheric_temperature"]] = data[["temp","atemp"]]
data.drop(["temp","atemp"], axis=1) # axis = 1 su kolone, axis = 0 su redovi! Obrisao sam temp i atemp

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0          1  2011-01-01       1   0     1        0        6           0   
1          2  2011-01-02       1   0     1        0        0           0   
2          3  2011-01-03       1   0     1        0        1           1   
3          4  2011-01-04       1   0     1        0        2           1   
4          5  2011-01-05       1   0     1        0        3           1   
..       ...         ...     ...  ..   ...      ...      ...         ...   
726      727  2012-12-27       1   1    12        0        4           1   
727      728  2012-12-28       1   1    12        0        5           1   
728      729  2012-12-29       1   1    12        0        6           0   
729      730  2012-12-30       1   1    12        0        0           0   
730      731  2012-12-31       1   1    12        0        1           1   

     weathersit       hum  windspeed  casual  registered   cnt  temperature  \
0             2  0.805833   0.160446     331         654   985     0.344167   
1             2  0.696087   0.248539     131         670   801     0.363478   
2             1  0.437273   0.248309     120        1229  1349     0.196364   
3             1  0.590435   0.160296     108        1454  1562     0.200000   
4             1  0.436957   0.186900      82        1518  1600     0.226957   
..          ...       ...        ...     ...         ...   ...          ...   
726           2  0.652917   0.350133     247        1867  2114     0.254167   
727           2  0.590000   0.155471     644        2451  3095     0.253333   
728           2  0.752917   0.124383     159        1182  1341     0.253333   
729           1  0.483333   0.350754     364        1432  1796     0.255833   
730           2  0.577500   0.154846     439        2290  2729     0.215833   

     atmospheric_temperature  
0                   0.363625  
1                   0.353739  
2                   0.189405  
3                   0.212122  
4                   0.229270  
..                       ...  
726                 0.226642  
727                 0.255046  
728                 0.242400  
729                 0.231700  
730                 0.223487  

[731 rows x 16 columns]

In [76]:
data.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0   
1        2  2011-01-02       1   0     1        0        0           0   
2        3  2011-01-03       1   0     1        0        1           1   
3        4  2011-01-04       1   0     1        0        2           1   
4        5  2011-01-05       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  temperature  atmospheric_temperature  
0   985     0.344167                 0.363625  
1   801     0.363478                 0.353739  
2  1349     0.196364                 0.189405  
3  1562     0.200000                 0.212122  
4  1600     0.226957                 0.229270

In [104]:
matrix = np.matrix([[5,2,5],[4,6]])
matrix

matrix([[list([5, 2, 5]), list([4, 6])]], dtype=object)

In [96]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
matrix1[2][2]

9

In [99]:
matrix1[matrix1<3]

array([1, 2])

In [102]:
matrix1.mean()

5.0